version: 0.2

env:
  variables:
    sonarProjectName: "test-deploy-app"

phases:
  install:
    commands:
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
      - sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      # - export CHROME_BIN=/usr/bin/chromium-browser
      - ls /usr/bin
      - which chrome
      - which google-chrome
      - export CHROME_BIN=/usr/bin/google-chrome
      - apt-get update
      # - apt-get --assume-yes install chromium-browser
      - apt-get install google-chrome-stable
      - echo test build started on `date`
  pre_build:
    commands:
      - echo pre build started on `date`
      - npm install
      - npm test
      - npm run e2e
      - npm run build
      - echo build completed on `date`
  build:
    commands:
      - echo testing started on `date`
      # - npm run unit-test-with-coverage
      # - npm run sonar-scanner
      - echo testing completed on `date`
  post_build:
    commands:
      - echo production build started on `date`
      - npm prune --production
      - echo production build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build'