version: 0.2

env:
  variables:
    sonarProjectName: "test-deploy-app"

phases:
  install:
    commands:
      - export CHROME_BIN=/usr/bin/chromium-browser
      - apt-get update
      - apt-get --assume-yes install chromium-browser
      - echo test build started on `date`
  pre_build:
    commands:
      - echo pre build started on `date`
      - npm install
      - npm test
      - npm run e2e
      - npm run build
      - echo build completed on `date`
  build:
    commands:
      - echo testing started on `date`
      # - npm run unit-test-with-coverage
      # - npm run sonar-scanner
      - echo testing completed on `date`
  post_build:
    commands:
      - echo production build started on `date`
      - npm prune --production
      - echo production build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build'